# Might be easier to work with this if everything is in English

columns_rename = {
	"ime": "title",
	"cijena": "price",
	"stanje": "condition",
	"lokacija": "location",
	"proizvodjac": "manufacturer",
	"model": "model",
	"godiste": "year",
	"kilometraza": "odometer",
	"kilovata": "kW",
	"kubikaza": "engine_volume",
	"gorivo": "fuel_type",
	"vrata": "doors",
	"konjskih_snaga": "hp",
	"pogon": "drive",
	"emisioni_standard": "emission_class",
	"transmisija": "transmission",
	"brzina": "gears",
	"registrovan_do": "registered_until",
	"prethodnih_vlasnika": "previous_owners",
	"sjedecih_mjesta": "seats",
	"turbo": "turbo",
	"strane_tablice": "foreign_license_plates",
	"registrovan": "registration",
	"ocarinjen": "customs_paid",
	"na_lizingu": "leasing",
	"servisna_knjiga": "service_history",
	"servo_volan": "servo",
	"tempomat": "cruise_control",
	"abs": "abs",
	"esp": "esp",
	"klima": "ac",
	"navigacija": "navigation",
	"alu_felge": "al_rims",
	"oldtimer": "oldtimer",
	"udaren": "damaged",
	"vrsta_oglasa": "ad_type",
	"datum_objave": "date_first_published",
	"broj_pregleda": "views",
	"radnja": "shop",
	"datum": "date",
}
